# Usar uma imagem Python slim compatível com ARM64 e amd64
FROM python:3.8-slim

# Set environment variables to prevent buffering
ENV PYTHONUNBUFFERED=1

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Install system dependencies for Python and PostgreSQL if needed
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    python3-dev \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Initialize the database
RUN python init_db.py

# Expose port 3111 for the application
EXPOSE 3111

# Define the command to run the application
CMD ["python", "app.py"]